### ISSUE TITLE
Exception in thread "Thread-0" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by yanghongXXL** [i02momuj/MLDA#1]
This happened to me now, whereas before it wasn't doing ang of that, don't know what's causing it.
![![Snipaste_2023-04-03_22-31-05](https://user-images.githubusercontent.com/29794345/229540794-12493a53-275c-4d37-82a4-4717795b076c.png)

**Comment by yanghongXXL** [comment]
```java
PS C:\Users\yhXXL\Desktop\MLDA_GUI_v1_2_4> java -jar MLDA.jar
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at mulan.data.MultiLabelInstances.loadLabelsMeta(MultiLabelInstances.java:540)
        at mulan.data.MultiLabelInstances.<init>(MultiLabelInstances.java:168)
        at app.RunApp.loadDataset(RunApp.java:5662)
        at app.RunApp.loadDataset(RunApp.java:4994)
        at app.RunApp.access$5100(RunApp.java:143)
        at app.RunApp$51.run(RunApp.java:3534)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 7 more
```

**Comment by i02momuj** [comment]
Hi Yang,
which Java version and OS are you using? In order to try to reproduce the error and check what is happening.

Besides, did it happen just as soon as you open MLDA, right? Or after doing any action on it.
Best.

**Comment by yanghongXXL** [comment]
Dear Jose,
Thank you very much for your reply.

The environment of my computer is:
Windows 11 64-bit
java version "19.0.2" 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

I am trying to use the file MLDA_GUI_v1_2_4. Open Windows PowerShell in this folder and type "java-jar mlda.jar" and the MLDA GUI will display normally.

But when I try to open MLDA's own datasets/emotionsMV.arff or some other data in the GUI, I get the error I described earlier. In addition, a moving pink window appears in the GUI. As a result, MLDA cannot load any data. When I run it on a different windows machine, something similar happens.
![image](https://user-images.githubusercontent.com/29794345/229780849-c6396eb8-e9ba-4ab8-80e5-0e3e8422d8c5.png)


Thank you very much for your help. Best wishes!

**Comment by yanghongXXL** [comment]
I switched to java8 and it worked. Thank you for your outstanding contributions in the field of multi-label!
Best wishes!
